//
//  DecimalFloat+Shortest.swift
//  ADFCore
//
//  Shortest round-trip decimal for a binary64 `Double` -- the formatting counterpart to the
//  Eisel-Lemire parser -- ported from Ulf Adams' Ryu `d2s` (the shortest, correctly-rounded,
//  round-to-nearest-ties-to-even algorithm; produces byte-identical digits to Dragonbox/Schubfach and
//  to Swift's own `Double.description`). It returns the decimal significand + exponent directly, so a
//  formatter writes digits straight into its output buffer instead of allocating an intermediate
//  `String` from `Double.description` and re-parsing it.
//
//  Contract: for a finite `v`, `shortestDouble(v)` returns `(negative, significand, exponent)` with
//  `v == (negative ? -1 : 1) * significand * 10^exponent`, `significand` carrying the fewest digits that
//  round-trips and no trailing zeros (`significand == 0` iff `v` is +/-0). Pure Swift, strict-memory-safe
//  (only `multipliedFullWidth`/`trailingZeroBitCount`/`bitPattern`). Verified in `ShortestDoubleTests`
//  to yield the exact same significant digits as `Double.description` over millions of values.
//
//  The two 128-bit tables (`doublePow5Split` = truncated 5^i; `doublePow5InvSplit` = its rounded-up
//  reciprocal, each 125 significant bits) are generated by exact big-integer arithmetic, never
//  hand-transcribed. Anchors: `doublePow5InvSplit[1] = 0x1999…_999A` (the 1/5 reciprocal).
//

extension DecimalFloat {
    @inline(__always)
    private static func log10Pow2(_ e: Int) -> Int { Int((UInt64(e) &* 78_913) >> 18) }
    @inline(__always)
    private static func log10Pow5(_ e: Int) -> Int { Int((UInt64(e) &* 732_923) >> 20) }
    @inline(__always)
    private static func pow5bits(_ e: Int) -> Int { Int((UInt64(e) &* 1_217_359) >> 19) + 1 }

    /// `(m * (mulHi:mulLo)) >> shift`, low 64 bits. `shift` is in `[122, 125]` here, so `shift - 64`
    /// is in `[0, 63]`.
    @inline(__always)
    private static func mulShift64(_ m: UInt64, _ mulLo: UInt64, _ mulHi: UInt64, _ shift: Int) -> UInt64 {
        let (b0hi, _) = m.multipliedFullWidth(by: mulLo)  // high 64 of m*mulLo
        let (b2hi, b2lo) = m.multipliedFullWidth(by: mulHi)
        let (sumLo, carry) = b2lo.addingReportingOverflow(b0hi)
        let sumHi = b2hi &+ (carry ? 1 : 0)
        let s = shift - 64
        if s == 0 { return sumLo }
        return (sumHi << (64 - s)) | (sumLo >> s)
    }

    /// vr / vp / vm for the three boundaries `4m` / `4m+2` / `4m-1-mmShift`, all multiply-shifted by `j`.
    @inline(__always)
    private static func mulShiftAll64(
        _ m: UInt64, _ mulLo: UInt64, _ mulHi: UInt64, _ j: Int, _ mmShift: UInt64
    ) -> (vr: UInt64, vp: UInt64, vm: UInt64) {
        let vp = mulShift64(4 &* m &+ 2, mulLo, mulHi, j)
        let vm = mulShift64(4 &* m &- 1 &- mmShift, mulLo, mulHi, j)
        let vr = mulShift64(4 &* m, mulLo, mulHi, j)
        return (vr, vp, vm)
    }

    /// Whether `value` has at least `p` factors of five.
    @inline(__always)
    private static func multipleOfPowerOf5(_ value: UInt64, _ p: Int) -> Bool {
        var v = value
        var count = 0
        while v % 5 == 0 {
            v /= 5
            count += 1
        }
        return count >= p
    }

    /// The Ryu decimal interval `[vm, vp]` bracketing `vr`, with the base-10 exponent and the
    /// trailing-zero flags the shortest-decimal search consumes.
    private struct DecimalInterval {
        var vr: UInt64
        var vp: UInt64
        var vm: UInt64
        var e10: Int
        var vmIsTrailingZeros: Bool
        var vrIsTrailingZeros: Bool
    }

    /// Ryu step 2: scale `m2 · 2^e2` into the decimal interval, splitting on the sign of `e2`
    /// (multiply by an inverse power of five, or by a power of five).
    ///
    /// Split out of ``shortestDouble(_:)`` along the algorithm's own seam — the reference
    /// implementation makes the same cut between interval computation and the shortest-decimal
    /// search. `@inline(__always)`, and the caller is not `@inlinable`, so this is code motion:
    /// the optimizer sees the same body it did before.
    @inline(__always)
    private static func decimalInterval(
        m2: UInt64, e2: Int, mv: UInt64, mmShift: UInt64, acceptBounds: Bool
    ) -> DecimalInterval {
        var vr: UInt64
        var vp: UInt64
        var vm: UInt64
        let e10: Int
        var vmIsTrailingZeros = false
        var vrIsTrailingZeros = false

        if e2 >= 0 {
            let q = log10Pow2(e2) - (e2 > 3 ? 1 : 0)
            e10 = q
            let k = 125 + pow5bits(q) - 1
            let i = -e2 + q + k
            (vr, vp, vm) = mulShiftAll64(m2, doublePow5InvSplit[2 * q], doublePow5InvSplit[2 * q + 1], i, mmShift)
            if q <= 21 {
                if mv % 5 == 0 {
                    vrIsTrailingZeros = multipleOfPowerOf5(mv, q)
                } else if acceptBounds {
                    vmIsTrailingZeros = multipleOfPowerOf5(mv &- 1 &- mmShift, q)
                } else if multipleOfPowerOf5(mv &+ 2, q) {
                    vp &-= 1
                }
            }
        } else {
            let q = log10Pow5(-e2) - (-e2 > 1 ? 1 : 0)
            e10 = q + e2
            let i = -e2 - q
            let k = pow5bits(i) - 125
            let j = q - k
            (vr, vp, vm) = mulShiftAll64(m2, doublePow5Split[2 * i], doublePow5Split[2 * i + 1], j, mmShift)
            if q <= 1 {
                vrIsTrailingZeros = true
                if acceptBounds {
                    vmIsTrailingZeros = mmShift == 1
                } else {
                    vp &-= 1
                }
            } else if q < 63 {
                vrIsTrailingZeros = (mv & ((UInt64(1) << q) - 1)) == 0
            }
        }

        return DecimalInterval(
            vr: vr, vp: vp, vm: vm, e10: e10,
            vmIsTrailingZeros: vmIsTrailingZeros, vrIsTrailingZeros: vrIsTrailingZeros)
    }

    /// Ryu step 3, exact branch: shorten `[vm, vp]` while either bound is known to have trailing
    /// zeros, so the round-to-even decision stays exact. Returns the output significand and how many
    /// digits were removed.
    @inline(__always)
    private static func shortestWithTrailingZeros(
        vr: inout UInt64, vp: inout UInt64, vm: inout UInt64,
        vmIsTrailingZeros: inout Bool, vrIsTrailingZeros: inout Bool,
        acceptBounds: Bool
    ) -> (output: UInt64, removed: Int) {
        var removed = 0
        var lastRemovedDigit: UInt8 = 0
        while vp / 10 > vm / 10 {
            vmIsTrailingZeros = vmIsTrailingZeros && (vm % 10 == 0)
            vrIsTrailingZeros = vrIsTrailingZeros && (lastRemovedDigit == 0)
            lastRemovedDigit = UInt8(vr % 10)
            vr /= 10
            vp /= 10
            vm /= 10
            removed += 1
        }
        if vmIsTrailingZeros {
            while vm % 10 == 0 {
                vrIsTrailingZeros = vrIsTrailingZeros && (lastRemovedDigit == 0)
                lastRemovedDigit = UInt8(vr % 10)
                vr /= 10
                vp /= 10
                vm /= 10
                removed += 1
            }
        }
        if vrIsTrailingZeros && lastRemovedDigit == 5 && vr % 2 == 0 {
            lastRemovedDigit = 4  // round to even
        }
        let roundUp = (vr == vm && (!acceptBounds || !vmIsTrailingZeros)) || lastRemovedDigit >= 5
        return (vr + (roundUp ? 1 : 0), removed)
    }

    /// Ryu step 3, common branch: neither bound has trailing zeros, so shortening needs no
    /// exactness tracking — two digits at a time first, then one.
    @inline(__always)
    private static func shortestFastPath(
        vr: inout UInt64, vp: inout UInt64, vm: inout UInt64
    ) -> (output: UInt64, removed: Int) {
        var removed = 0
        var roundUp = false
        if vp / 100 > vm / 100 {
            roundUp = (vr % 100) >= 50
            vr /= 100
            vp /= 100
            vm /= 100
            removed += 2
        }
        while vp / 10 > vm / 10 {
            roundUp = (vr % 10) >= 5
            vr /= 10
            vp /= 10
            vm /= 10
            removed += 1
        }
        return (vr + ((vr == vm || roundUp) ? 1 : 0), removed)
    }

    /// The shortest round-trip decimal for a finite `v` (Ryu `d2s`). See the file contract.
    public static func shortestDouble(_ v: Double) -> (negative: Bool, significand: UInt64, exponent: Int) {
        let bits = v.bitPattern
        let negative = (bits >> 63) != 0
        let ieeeExponent = Int((bits >> 52) & 0x7FF)
        let ieeeMantissa = bits & 0x000F_FFFF_FFFF_FFFF

        if ieeeExponent == 0 && ieeeMantissa == 0 {
            return (negative, 0, 0)  // +/-0 -> zero sentinel
        }

        var e2: Int
        var m2: UInt64
        if ieeeExponent == 0 {
            e2 = 1 - 1023 - 52 - 2
            m2 = ieeeMantissa
        } else {
            e2 = ieeeExponent - 1023 - 52 - 2
            m2 = (UInt64(1) << 52) | ieeeMantissa
        }
        let even = (m2 & 1) == 0
        let acceptBounds = even

        let mv = 4 &* m2
        let mmShift: UInt64 = (ieeeMantissa != 0 || ieeeExponent <= 1) ? 1 : 0

        let interval = decimalInterval(
            m2: m2, e2: e2, mv: mv, mmShift: mmShift, acceptBounds: acceptBounds)
        var vr = interval.vr
        var vp = interval.vp
        var vm = interval.vm
        let e10 = interval.e10
        var vmIsTrailingZeros = interval.vmIsTrailingZeros
        var vrIsTrailingZeros = interval.vrIsTrailingZeros

        // Find the shortest decimal in [vm, vp] containing vr, tracking round-to-even.
        let output: UInt64
        let removed: Int
        if vmIsTrailingZeros || vrIsTrailingZeros {
            (output, removed) = shortestWithTrailingZeros(
                vr: &vr, vp: &vp, vm: &vm,
                vmIsTrailingZeros: &vmIsTrailingZeros, vrIsTrailingZeros: &vrIsTrailingZeros,
                acceptBounds: acceptBounds)
        } else {
            (output, removed) = shortestFastPath(vr: &vr, vp: &vp, vm: &vm)
        }

        var sig = output
        var exp = e10 + removed
        if sig != 0 {
            while sig % 10 == 0 {
                sig /= 10
                exp += 1
            }
        }
        return (negative, sig, exp)
    }
}
